# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0ae2d50594ccde6661b85ee3b831ae69963e459b1e38f44d70f4e7e6b0734eef381803442065511fcfb852b37d472310dfafe6beaedee9f504ed4117d07e133

test:
  secret_key_base: a516ac880841591cc2eb1530cea4d2a9eff51f0d4232fa9cb5b98b18794e93c2eae74503ce261fbac6489b0831d4a61a94bd000e37c4f29cbd3aef290582fa1a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
